core/urls.py
from django.urls import path

from core.views import (
    TaskListView,
    TaskUpdateView,
    TaskCreateView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskDeleteView,
    task_status_change,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/change_status/", task_status_change, name="task-status-change"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "core"

todo_list/urls.py
"""
todo_list URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path('__debug__/', include('debug_toolbar.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return str(self.name)


class Task(models.Model):
    content = models.CharField(max_length=500)
    creation_date = models.DateTimeField(auto_now_add=True, )
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-creation_date"]

core/forms.py
from django import forms

from core.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    deadline = forms.DateTimeField(
        widget=forms.widgets.DateTimeInput(
            attrs={"type": "datetime-local"}
        ),
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

core/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from core.forms import TaskForm
from core.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tags")
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("core:task-list")


def task_status_change(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True

    task.save()

    return HttpResponseRedirect(reverse("core:task-list"))


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 3


class TagCreateView(generic.CreateView):
    model = Tag
    success_url = reverse_lazy("core:tag-list")
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    success_url = reverse_lazy("core:tag-list")
    fields = "__all__"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("core:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>TODO</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    {% include "includes/sidebar.html" %}
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

            </div>
        </div>
    </div>
</body>

</html>

templates/core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Tag</h1>

    <p>Are you sure you want to delete the tag: "{{ tag.name }}"?</p>

    <form action=""  method="POST">
        {%  csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
        <a href="{% url 'core:tag-list' %}" class="btn btn-primary">Cancel</a>
    </form>

{% endblock %}

templates/core/tag_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}

    <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit">
    </form>

{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}

{% block content %}

    <h1>
        Tags
    <a class="btn btn-primary btn-lg" style="float: right" href="{%  url 'core:tag-create' %}">
        Add
    </a>
    </h1>
    <br>
    {% if tag_list %}
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>

            {% for tag in tag_list %}
                <tr>
                    <td>{{ tag.name }}</td>
                    <td>
                        <a class="btn btn-secondary" href="{% url 'core:tag-update' pk=tag.id %}">Update</a>
                    </td>
                    <td>
                        <a class="btn btn-secondary" href="{% url 'core:tag-delete' pk=tag.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <p>No Tags!</p>
    {% endif %}

{% endblock %}

templates/core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Task</h1>

    <p>Are you sure you want to delete the task: "{{ task.content }}"?</p>

    <form action=""  method="POST">
        {%  csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
        <a href="{% url 'core:task-list' %}" class="btn btn-primary">Cancel</a>
    </form>

{% endblock %}

templates/core/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

    <h1>{{ object|yesno:"Update,Create" }} Task</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit">
    </form>

{% endblock %}

templates/core/task_list.html
{% extends "base.html" %}

{% block content %}

    <h1>
        TODO list
        <a style="float: right" class="btn btn-primary btn-lg" href="{% url 'core:task-create' %}">
            Add task
        </a>
    </h1>
    <br>
    {% if task_list %}
        {% for task in task_list %}
            <p>
                <strong>{{ task.content }}
                    {% if task.is_done %}
                        <span class="text-success"> Done</span>
                        <a style="float: right" class="btn btn-secondary" href="{% url 'core:task-status-change' pk=task.id %}">Undo</a>
                    {% else %}
                        <span class="text-danger"> Not done</span>
                        <a style="float: right" class="btn btn-success" href="{% url 'core:task-status-change' pk=task.id %}">Complete</a>
                    {% endif %}
                </strong>
            </p>
            <p>
                Created: {{ task.creation_date }}
                {% if task.deadline %}
                    <span style="color: mediumpurple">Deadline: {{ task.deadline }}</span>
                {% endif %}
            </p>
            <p>
                <span class="text-muted">
                    Tags:
                    {% for tag in task.tags.all %}
                        {{ tag.name }}
                    {% endfor %}
                </span>
                <a href="{% url 'core:task-update' pk=task.id %}">Update</a>
                |
                <a href="{% url 'core:task-delete' pk=task.id %}">Delete</a>
            </p>
            <hr>
        {% endfor %}

    {% else %}
        No tasks!
    {% endif %}

{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}

        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                        prev
                    </a>
                </li>
            {% endif %}

            <li class="page-item active">
                <span class="page-link">
                    {{ page_obj.number }} of {{ paginator.num_pages }}
                </span>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                        next
                    </a>
                </li>
            {% endif %}
        </ul>

{% endif %}

templates/includes/sidebar.html
<div class="sidebar-nav list-group">
    <a class="list-group-item list-group-item-action" href="{% url 'core:task-list' %}">
        Home
    </a>
    <a class="list-group-item list-group-item-action" href="{% url 'core:tag-list' %}">
        Tags
    </a>
</div>